### ISSUE TITLE
Environment vars

### ISSUE THREAD

**Issue by heyoka** [Kyorai/cuttlefish#7]
I would like to warm up an old issue from the original basho cuttlefish repository:
[Environment Variables](https://github.com/basho/cuttlefish/issues/135) 
Is there any change for such a feature ? 
I woud need this for different scenarios where config via Environment vars is mandatory.

Thank you.

**Comment by michaelklishin** [comment]
Environment variables are "arbitrarily typed", unvalidated inputs so using them should be a last resort measure. However, I can see how this can be useful in a narrow number of cases.

If Cuttlefish expanded such variables before performing validation and would take the key type into account when parsing the values, it might work well. Rendering values verbatim is also an option.

We need someone interested to put together a specific proposal as to how exactly such environment variable support would work. For example, we can add a built-in function instead of a special syntax. We need to decide what to do with the implicit typing of raw env variable values.

@heyoka would you be up for putting together a specific proposal with some examples that address the typing question above?

**Comment by michaelklishin** [comment]
Closing due to the lack of activity (and interest in env variable support from some of the heaviest users of Cuttlefish today).
